[llm] # llm config
name = "groq:llama-3.3-70b-versatile"
base_url = ""
api_key = "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"
max_tokens = 1024
temperature = 0.0
prompt= '''
    You are an AI assistant to answer questions.
'''

[logfire] # log fire config
token = "SGtFQXq0qRhrb6xKjhYt0pGkWSVHY395z3cv4X10jV6C"

  